<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('nilai_realisasi', function (Blueprint $table) {
            $table->increments('id_nr');
            $table->integer('id_skpnr');
            $table->integer('id_ka')->nullable();
            $table->integer('raka')->nullable();
            $table->integer('rkua')->nullable();
            $table->string('routa')->nullable();
            $table->integer('rmuta')->nullable();
            $table->integer('rtimea')->nullable();
            $table->string('rtmda')->nullable();
            $table->integer('rbiayaa')->nullable();
            $table->integer('perhitungan_a')->nullable();
            $table->string('skp_a')->nullable();
            $table->integer('id_kb')->nullable();
            $table->integer('rakb')->nullable();
            $table->integer('rkub')->nullable();
            $table->string('routb')->nullable();
            $table->integer('rmutb')->nullable();
            $table->integer('rtimeb')->nullable();
            $table->string('rtmdb')->nullable();
            $table->integer('rbiayab')->nullable();
            $table->integer('perhitungan_b')->nullable();
            $table->string('skp_b')->nullable();
            $table->integer('id_kc')->nullable();
            $table->integer('rakc')->nullable();
            $table->integer('rkuc')->nullable();
            $table->string('routc')->nullable();
            $table->integer('rmutc')->nullable();
            $table->integer('rtimec')->nullable();
            $table->string('rtmdc')->nullable();
            $table->integer('rbiayac')->nullable();
            $table->integer('perhitungan_c')->nullable();
            $table->string('skp_c')->nullable();
            $table->integer('id_kd')->nullable();
            $table->integer('rakd')->nullable();
            $table->integer('rkud')->nullable();
            $table->string('routd')->nullable();
            $table->integer('rmutd')->nullable();
            $table->integer('rtimed')->nullable();
            $table->string('rtmdd')->nullable();
            $table->integer('rbiayad')->nullable();
            $table->integer('perhitungan_d')->nullable();
            $table->string('skp_d')->nullable();
            $table->integer('id_ke')->nullable();
            $table->integer('rake')->nullable();
            $table->integer('rkue')->nullable();
            $table->string('route')->nullable();
            $table->integer('rmute')->nullable();
            $table->integer('rtimee')->nullable();
            $table->string('rtmde')->nullable();
            $table->integer('rbiayae')->nullable();
            $table->integer('perhitungan_e')->nullable();
            $table->string('skp_e')->nullable();
            $table->integer('id_kf')->nullable();
            $table->integer('rakf')->nullable();
            $table->integer('rkuf')->nullable();
            $table->string('routf')->nullable();
            $table->integer('rmutf')->nullable();
            $table->integer('rtimef')->nullable();
            $table->string('rtmdf')->nullable();
            $table->integer('rbiayaf')->nullable();
            $table->integer('perhitungan_f')->nullable();
            $table->string('skp_f')->nullable();
            $table->integer('id_kg')->nullable();
            $table->integer('rakg')->nullable();
            $table->integer('rkug')->nullable();
            $table->string('routg')->nullable();
            $table->integer('rmutg')->nullable();
            $table->integer('rtimeg')->nullable();
            $table->string('rtmdg')->nullable();
            $table->integer('rbiayag')->nullable();
            $table->integer('perhitungan_g')->nullable();
            $table->string('skp_g')->nullable();
            $table->integer('id_kh')->nullable();
            $table->integer('rakh')->nullable();
            $table->integer('rkuh')->nullable();
            $table->string('routh')->nullable();
            $table->integer('rmuth')->nullable();
            $table->integer('rtimeh')->nullable();
            $table->string('rtmdh')->nullable();
            $table->integer('rbiayah')->nullable();
            $table->integer('perhitungan_h')->nullable();
            $table->string('skp_h')->nullable();
            $table->integer('id_ki')->nullable();
            $table->integer('raki')->nullable();
            $table->integer('rkui')->nullable();
            $table->string('routi')->nullable();
            $table->integer('rmuti')->nullable();
            $table->integer('rtimei')->nullable();
            $table->string('rtmdi')->nullable();
            $table->integer('rbiayai')->nullable();
            $table->integer('perhitungan_i')->nullable();
            $table->string('skp_i')->nullable();
            $table->integer('id_kj')->nullable();
            $table->integer('rakj')->nullable();
            $table->integer('rkuj')->nullable();
            $table->string('routj')->nullable();
            $table->integer('rmutj')->nullable();
            $table->integer('rtimej')->nullable();
            $table->string('rtmdj')->nullable();
            $table->integer('rbiayaj')->nullable();
            $table->integer('perhitungan_j')->nullable();
            $table->string('skp_j')->nullable();
            $table->integer('id_kk')->nullable();
            $table->integer('rakk')->nullable();
            $table->integer('rkuk')->nullable();
            $table->string('routk')->nullable();
            $table->integer('rmutk')->nullable();
            $table->integer('rtimek')->nullable();
            $table->string('rtmdk')->nullable();
            $table->integer('rbiayak')->nullable();
            $table->integer('perhitungan_k')->nullable();
            $table->string('skp_k')->nullable();
            $table->integer('id_kl')->nullable();
            $table->integer('rakl')->nullable();
            $table->integer('rkul')->nullable();
            $table->string('routl')->nullable();
            $table->integer('rmutl')->nullable();
            $table->integer('rtimel')->nullable();
            $table->string('rtmdl')->nullable();
            $table->integer('rbiayal')->nullable();
            $table->integer('perhitungan_l')->nullable();
            $table->string('skp_l')->nullable();
            $table->integer('id_km')->nullable();
            $table->integer('rakm')->nullable();
            $table->integer('rkum')->nullable();
            $table->string('routm')->nullable();
            $table->integer('rmutm')->nullable();
            $table->integer('rtimem')->nullable();
            $table->string('rtmdm')->nullable();
            $table->integer('rbiayam')->nullable();
            $table->integer('perhitungan_m')->nullable();
            $table->string('skp_m')->nullable();
            $table->integer('id_kn')->nullable();
            $table->integer('rakn')->nullable();
            $table->integer('rkun')->nullable();
            $table->string('routn')->nullable();
            $table->integer('rmutn')->nullable();
            $table->integer('rtimen')->nullable();
            $table->string('rtmdn')->nullable();
            $table->integer('rbiayan')->nullable();
            $table->integer('perhitungan_n')->nullable();
            $table->string('skp_n')->nullable();
            $table->integer('id_ko')->nullable();
            $table->integer('rako')->nullable();
            $table->integer('rkuo')->nullable();
            $table->string('routo')->nullable();
            $table->integer('rmuto')->nullable();
            $table->integer('rtimeo')->nullable();
            $table->string('rtmdo')->nullable();
            $table->integer('rbiayao')->nullable();
            $table->integer('perhitungan_o')->nullable();
            $table->string('skp_o')->nullable();
            $table->integer('id_kp')->nullable();
            $table->integer('rakp')->nullable();
            $table->integer('rkup')->nullable();
            $table->string('routp')->nullable();
            $table->integer('rmutp')->nullable();
            $table->integer('rtimep')->nullable();
            $table->string('rtmdp')->nullable();
            $table->integer('rbiayap')->nullable();
            $table->integer('perhitungan_p')->nullable();
            $table->string('skp_p')->nullable();
            $table->string('dnta')->nullable();
            $table->string('dntb')->nullable();
            $table->string('dntc')->nullable();
            $table->string('dntd')->nullable();
            $table->string('tnr')->nullable();
            $table->string('snr')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('nilai_realisasi');
    }
};
