<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('nilai_target', function (Blueprint $table) {
            $table->increments('id_nt');
            $table->integer('id_skpnt');
            $table->integer('id_ka')->nullable();
            $table->integer('aka')->nullable();
            $table->integer('kua')->nullable();
            $table->string('outa')->nullable();
            $table->integer('muta')->nullable();
            $table->integer('timea')->nullable();
            $table->string('tmda')->nullable();
            $table->integer('biayaa')->nullable();
            $table->integer('id_kb')->nullable();
            $table->integer('akb')->nullable();
            $table->integer('kub')->nullable();
            $table->string('outb')->nullable();
            $table->integer('mutb')->nullable();
            $table->integer('timeb')->nullable();
            $table->string('tmdb')->nullable();
            $table->integer('biayab')->nullable();
            $table->integer('id_kc')->nullable();
            $table->integer('akc')->nullable();
            $table->integer('kuc')->nullable();
            $table->string('outc')->nullable();
            $table->integer('mutc')->nullable();
            $table->integer('timec')->nullable();
            $table->string('tmdc')->nullable();
            $table->integer('biayac')->nullable();
            $table->integer('id_kd')->nullable();
            $table->integer('akd')->nullable();
            $table->integer('kud')->nullable();
            $table->string('outd')->nullable();
            $table->integer('mutd')->nullable();
            $table->integer('timed')->nullable();
            $table->string('tmdd')->nullable();
            $table->integer('biayad')->nullable();
            $table->integer('id_ke')->nullable();
            $table->integer('ake')->nullable();
            $table->integer('kue')->nullable();
            $table->string('oute')->nullable();
            $table->integer('mute')->nullable();
            $table->integer('timee')->nullable();
            $table->string('tmde')->nullable();
            $table->integer('biayae')->nullable();
            $table->integer('id_kf')->nullable();
            $table->integer('akf')->nullable();
            $table->integer('kuf')->nullable();
            $table->string('outf')->nullable();
            $table->integer('mutf')->nullable();
            $table->integer('timef')->nullable();
            $table->string('tmdf')->nullable();
            $table->integer('biayaf')->nullable();
            $table->integer('id_kg')->nullable();
            $table->integer('akg')->nullable();
            $table->integer('kug')->nullable();
            $table->string('outg')->nullable();
            $table->integer('mutg')->nullable();
            $table->integer('timeg')->nullable();
            $table->string('tmdg')->nullable();
            $table->integer('biayag')->nullable();
            $table->integer('id_kh')->nullable();
            $table->integer('akh')->nullable();
            $table->integer('kuh')->nullable();
            $table->string('outh')->nullable();
            $table->integer('muth')->nullable();
            $table->integer('timeh')->nullable();
            $table->string('tmdh')->nullable();
            $table->integer('biayah')->nullable();
            $table->integer('id_ki')->nullable();
            $table->integer('aki')->nullable();
            $table->integer('kui')->nullable();
            $table->string('outi')->nullable();
            $table->integer('muti')->nullable();
            $table->integer('timei')->nullable();
            $table->string('tmdi')->nullable();
            $table->integer('biayai')->nullable();
            $table->integer('id_kj')->nullable();
            $table->integer('akj')->nullable();
            $table->integer('kuj')->nullable();
            $table->string('outj')->nullable();
            $table->integer('mutj')->nullable();
            $table->integer('timej')->nullable();
            $table->string('tmdj')->nullable();
            $table->integer('biayaj')->nullable();
            $table->integer('id_kk')->nullable();
            $table->integer('akk')->nullable();
            $table->integer('kuk')->nullable();
            $table->string('outk')->nullable();
            $table->integer('mutk')->nullable();
            $table->integer('timek')->nullable();
            $table->string('tmdk')->nullable();
            $table->integer('biayak')->nullable();
            $table->integer('id_kl')->nullable();
            $table->integer('akl')->nullable();
            $table->integer('kul')->nullable();
            $table->string('outl')->nullable();
            $table->integer('mutl')->nullable();
            $table->integer('timel')->nullable();
            $table->string('tmdl')->nullable();
            $table->integer('biayal')->nullable();
            $table->integer('id_km')->nullable();
            $table->integer('akm')->nullable();
            $table->integer('kum')->nullable();
            $table->string('outm')->nullable();
            $table->integer('mutm')->nullable();
            $table->integer('timem')->nullable();
            $table->string('tmdm')->nullable();
            $table->integer('biayam')->nullable();
            $table->integer('id_kn')->nullable();
            $table->integer('akn')->nullable();
            $table->integer('kun')->nullable();
            $table->string('outn')->nullable();
            $table->integer('mutn')->nullable();
            $table->integer('timen')->nullable();
            $table->string('tmdn')->nullable();
            $table->integer('biayan')->nullable();
            $table->integer('id_ko')->nullable();
            $table->integer('ako')->nullable();
            $table->integer('kuo')->nullable();
            $table->string('outo')->nullable();
            $table->integer('muto')->nullable();
            $table->integer('timeo')->nullable();
            $table->string('tmdo')->nullable();
            $table->integer('biayao')->nullable();
            $table->integer('id_kp')->nullable();
            $table->integer('akp')->nullable();
            $table->integer('kup')->nullable();
            $table->string('outp')->nullable();
            $table->integer('mutp')->nullable();
            $table->integer('timep')->nullable();
            $table->string('tmdp')->nullable();
            $table->integer('biayap')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('nilai_target');
    }
};
